const RAW_ASSET_ROOT='https://raw.githubusercontent.com/HungMCLe/Swordxstafd-datamine/claude/swordxstaff-datamining-2p1ywk/web/dist/assets';
const FEATURE_SIZE=18;
const vectorCache=new Map();
const FANTOMONS=[1600,'Falko',1601,'Boaro',1602,'Mandragora',1603,'Zeioletus',1604,'Terragon',1605,'Sylvaerie',1606,'Kels',1607,'Armopi',1608,'Herbote',1609,'Nyxarchon',1610,'Aegiswing',1611,'Pandarial',1612,'Chomusuke',1613,'Cabbage Dog',1614,'Prismora',1615,'Luminarch Steed'].reduce((a,v,i,x)=>{if(i%2===0)a.push({id:v,name:x[i+1]});return a},[]);
let appRef=null,installed=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function scopePreviewId(scope){return scope==='my'?'buildScreenshotPreviewV58':'pvpScreenshotPreviewV62'}
function canonicalUrl(raw){raw=String(raw||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw))return raw;const x=raw.replace(/^\.\//,'').replace(/^\//,'');return x.startsWith('assets/')?`${RAW_ASSET_ROOT}/${x.slice(7)}`:''}
function iconUrl(item,kind){const direct=canonicalUrl(item?.icon||item?.image||item?.img);if(direct)return direct;if((kind==='Technique'||kind==='Charm')&&Number.isFinite(+item?.id))return `${RAW_ASSET_ROOT}/skills/skill_${+item.id}.png`;if(kind==='Fantomon'&&Number.isFinite(+item?.id))return `${RAW_ASSET_ROOT}/pets/pet_${+item.id}.png`;const iconId=item?.iconId??item?.IconId??item?.icon_id;if((kind==='Relic'||kind==='Gear')&&Number.isFinite(+iconId))return `${RAW_ASSET_ROOT}/icons/${+iconId}.png`;return''}
function fallbackCatalog(scope){const cls=scope==='pvpEnemy'?document.getElementById('pvpEnemyClass')?.value:document.getElementById('myClass')?.value;return{className:cls||'',skills:appRef?.DM?.skills||[],fantomons:FANTOMONS,relics:appRef?.extras?.relicCatalog||[],gear:[...(appRef?.DM?.gear||[]),...(appRef?.extras?.inventory||[])]}}
function catalog(scope,kind){const c=appRef?.screenshotCatalog?.(scope)||fallbackCatalog(scope);let rows=[];if(kind==='Technique'||kind==='Charm'){rows=(c.skills||[]).filter(x=>x.kind===kind);const lineage=c.className&&appRef?.classLineage?.(c.className);if(Array.isArray(lineage)&&lineage.length)rows=rows.filter(x=>lineage.includes(x.cls))}else if(kind==='Fantomon')rows=c.fantomons||FANTOMONS;else if(kind==='Relic')rows=c.relics||[];else rows=c.gear||[];const seen=new Set();return rows.map(item=>({item,url:iconUrl(item,kind)})).filter(x=>x.item?.name&&x.url&&!seen.has(x.item.name)&&(seen.add(x.item.name),true))}
function loadImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(Error('image unavailable'));im.src=url})}
function vector(source,sx,sy,sw,sh){const c=document.createElement('canvas');c.width=FEATURE_SIZE;c.height=FEATURE_SIZE;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,sx,sy,sw,sh,0,0,FEATURE_SIZE,FEATURE_SIZE);const d=ctx.getImageData(0,0,FEATURE_SIZE,FEATURE_SIZE).data,v=[];for(let i=0;i<d.length;i+=4){const a=d[i+3]/255,b=245*(1-a);v.push(d[i]*a+b,d[i+1]*a+b,d[i+2]*a+b)}const mean=v.reduce((a,b)=>a+b,0)/v.length;let n=0;for(let i=0;i<v.length;i++){v[i]-=mean;n+=v[i]*v[i]}n=Math.sqrt(n)||1;return v.map(x=>x/n)}
async function canonicalVector(url){if(vectorCache.has(url))return vectorCache.get(url);const p=loadImage(url).then(im=>{const pad=.07;return vector(im,im.naturalWidth*pad,im.naturalHeight*pad,im.naturalWidth*(1-pad*2),im.naturalHeight*(1-pad*2))}).catch(()=>null);vectorCache.set(url,p);return p}
function crops(img,e){const r=img.getBoundingClientRect(),x=(e.clientX-r.left)*img.naturalWidth/r.width,y=(e.clientY-r.top)*img.naturalHeight/r.height,min=Math.min(img.naturalWidth,img.naturalHeight),sizes=[.045,.06,.08,.10,.13,.17].map(f=>Math.max(34,Math.min(240,Math.round(min*f))));return [...new Set(sizes)].map(size=>{const sx=Math.max(0,Math.min(img.naturalWidth-size,Math.round(x-size/2))),sy=Math.max(0,Math.min(img.naturalHeight-size,Math.round(y-size/2)));return vector(img,sx,sy,size,size)})}
function sim(a,b){if(!a||!b||a.length!==b.length)return-1;let d=0;for(let i=0;i<a.length;i++)d+=a[i]*b[i];return(Math.max(-1,Math.min(1,d))+1)/2}
async function mapLimit(rows,limit,fn){let i=0;const out=new Array(rows.length);async function worker(){while(i<rows.length){const j=i++;out[j]=await fn(rows[j])}}await Promise.all(Array.from({length:Math.min(limit,rows.length)},worker));return out}
function confidence(score,margin){return score>=.88&&margin>=.018?'High':score>=.79?'Medium':'Low'}
function localApply(scope,kind,item,slot){const i=Math.max(0,Math.min(3,+slot||0));if(kind==='Charm'){const p=scope==='my'?'ch':'pech',el=document.getElementById(`${p}Name${i}`);if(!el)return false;el.value=item.name;el.dispatchEvent(new Event('change',{bubbles:true}));return true}if(kind==='Technique'){const p=scope==='my'?'sk':'pesk',el=document.getElementById(`${p}Name${i}`);if(!el)return false;el.value=item.name;document.getElementById(`${p}Element${i}`)&&(document.getElementById(`${p}Element${i}`).value=item.element||'Physical');document.getElementById(`${p}Hits${i}`)&&(document.getElementById(`${p}Hits${i}`).value=item.hits||1);el.dispatchEvent(new Event('change',{bubbles:true}));return true}if(kind==='Fantomon'){const p=scope==='my'?'myFantomon':'pvpEnemyFantomon',el=document.getElementById(`${p}Name`);if(!el)return false;el.value=item.name;const on=document.getElementById(`${p}Enabled`);if(on)on.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}));return true}return false}
async function matchAt(scope,kind,img,e,tool){const status=tool.querySelector('[data-icon-status]'),results=tool.querySelector('[data-icon-results]'),candidates=catalog(scope,kind);results.innerHTML='';if(!candidates.length){status.textContent=`No verified ${kind.toLowerCase()} image mapping is available yet.`;return}status.textContent=`Checking ${candidates.length} possible ${kind.toLowerCase()} icons…`;const q=crops(img,e),scored=(await mapLimit(candidates,8,async row=>{const v=await canonicalVector(row.url);if(!v)return null;return{...row,score:Math.max(...q.map(x=>sim(x,v)))}})).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,3);if(!scored.length){status.textContent='Reference images could not be loaded. Check your connection and try again.';return}scored.forEach((r,i)=>r.conf=confidence(r.score,r.score-(scored[i+1]?.score||0)));status.textContent='Best visual matches. Confirm the item before applying it.';results.innerHTML=scored.map((r,i)=>`<div class="icon-match-result-v71" data-i="${i}"><img src="${esc(r.url)}" alt=""><div><b>${esc(r.item.name)}</b><span>${r.conf} confidence${r.item.cls?` · ${esc(r.item.cls)}`:''}</span></div>${kind==='Technique'||kind==='Charm'?`<label>Slot <select data-slot>${[1,2,3,4].map(n=>`<option value="${n-1}">${n}</option>`).join('')}</select></label>`:''}${['Technique','Charm','Fantomon'].includes(kind)?'<button class="btn small" data-apply>Apply</button>':'<span class="hint">Identification only</span>'}</div>`).join('');results.querySelectorAll('[data-apply]').forEach(btn=>btn.onclick=()=>{const row=btn.closest('[data-i]'),r=scored[+row.dataset.i],slot=+(row.querySelector('[data-slot]')?.value||0),ok=appRef?.applyScreenshotImageMatch?.(scope,kind,r.item,slot)??localApply(scope,kind,r.item,slot);status.textContent=ok?`${r.item.name} applied. Review the field before simulating.`:`${r.item.name} identified. Select it manually.`})}
function attach(scope,host){if(!host||host.querySelector('.icon-match-tool-v71'))return;const tool=document.createElement('div');tool.className='icon-match-tool-v71';tool.innerHTML=`<div class="icon-match-head-v71"><div><b>Identify an unlabeled icon</b><span>Choose the item type, then click the icon in the screenshot.</span></div><label>Icon type <select data-kind><option>Technique</option><option>Charm</option><option>Fantomon</option><option>Relic</option><option>Gear</option></select></label></div><div class="hint" data-icon-status>Nothing changes until you confirm a match.</div><div data-icon-results></div>`;host.appendChild(tool);const preview=document.getElementById(scopePreviewId(scope));preview?.querySelectorAll('img').forEach(img=>{img.classList.add('screenshot-matchable-v71');if(img.dataset.iconMatcherV71)return;img.dataset.iconMatcherV71='1';img.title='Click an item icon to identify it';img.addEventListener('click',e=>matchAt(scope,tool.querySelector('[data-kind]').value,img,e,tool))})}
function scan(){for(const [scope,id] of [['my','buildScreenshotReviewV58'],['pvpEnemy','pvpScreenshotReviewV62']]){const h=document.getElementById(id);if(h&&!h.classList.contains('hidden'))attach(scope,h)}}
function styles(){if(document.getElementById('icon-match-style-v71'))return;const s=document.createElement('style');s.id='icon-match-style-v71';s.textContent=`.screenshot-matchable-v71{height:auto!important;max-height:360px!important;max-width:min(100%,420px)!important;width:auto!important;object-fit:contain!important;cursor:crosshair}.icon-match-tool-v71{margin-top:12px;padding:12px;border:1px solid var(--border,#cbd5e1);border-radius:12px}.icon-match-head-v71{display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap}.icon-match-head-v71 span,.icon-match-result-v71 span{display:block;font-size:.82rem;opacity:.75}.icon-match-result-v71{display:grid;grid-template-columns:48px 1fr auto auto;gap:10px;align-items:center;margin-top:8px;padding:8px;border-radius:10px;background:rgba(127,127,127,.07)}.icon-match-result-v71 img{width:44px;height:44px;object-fit:contain}@media(max-width:700px){.icon-match-result-v71{grid-template-columns:44px 1fr}.icon-match-result-v71>label,.icon-match-result-v71>button,.icon-match-result-v71>.hint{grid-column:2}}`;document.head.appendChild(s)}
export function init(app,tab){appRef=app;styles();if(!installed){installed=true;new MutationObserver(scan).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('sxs:screenshot-review-rendered',scan)}scan();if(tab==='pvp'){const c=document.getElementById('cancelPvpV7');if(c&&!c.dataset.moduleWired){c.dataset.moduleWired='1';c.addEventListener('click',()=>app.cancel?.('pvp'))}}}
