'use strict';
const cancelled=new Set();
function post(id,type,data={}){postMessage({id,type,...data})}
function topInsert(arr,row,n){let i=arr.findIndex(x=>row.score>x.score);if(i<0)i=arr.length;arr.splice(i,0,row);if(arr.length>n)arr.length=n}
function comboRank(id,p){const a=p.candidates||[],k=Math.max(1,p.choose||4),limit=Math.max(1,p.limit||100000),topN=Math.max(1,p.topN||100),top=[];let seen=0,last=0;const cur=[];
 function rec(start,score){if(cancelled.has(id))return;if(cur.length===k){seen++;topInsert(top,{ids:cur.map(i=>a[i].id),score},topN);if(seen-last>=1000){last=seen;post(id,'progress',{done:seen,total:limit})}return}for(let i=start;i<=a.length-(k-cur.length)&&seen<limit;i++){cur.push(i);rec(i+1,score+(+a[i].score||0));cur.pop();if(cancelled.has(id)||seen>=limit)return}}
 rec(0,0);return{rows:top,seen};}
function cartesianRank(id,p){const groups=p.groups||[],limit=Math.max(1,p.limit||100000),topN=Math.max(1,p.topN||150),setBonus=p.setBonus||{},top=[];let seen=0,last=0;const cur=[];
 function leaf(score){const counts={};for(const x of cur)if(x.set)counts[x.set]=(counts[x.set]||0)+1;for(const [set,rules] of Object.entries(setBonus)){const n=counts[set]||0;for(const r of rules||[])if(n>=r.pieces)score+=+r.rough||0}seen++;topInsert(top,{ids:cur.map(x=>x.id),score},topN);if(seen-last>=1000){last=seen;post(id,'progress',{done:seen,total:limit})}}
 function rec(g,score){if(cancelled.has(id)||seen>=limit)return;if(g>=groups.length){leaf(score);return}for(const x of groups[g]){cur.push(x);rec(g+1,score+(+x.score||0));cur.pop();if(cancelled.has(id)||seen>=limit)return}}
 rec(0,0);return{rows:top,seen};}
function effectAt(e,t){if(!e)return 0;const cd=Math.max(1,+e.cd||1),dur=Math.max(1,+e.duration||1),first=Math.max(0,+e.first||0);if(t<first)return 0;const phase=(t-first)%cd;return phase<dur?(+e.value||0):0}
function timelineScore(primary,effects,turns){let total=0,events=[],baseD=+primary.damagePerAction||0,baseSpd=Math.max(1,+primary.spd||1),enemySpd=Math.max(1,+primary.enemySpd||1),scale=Math.max(.0001,+primary.speedScale||1),enemyScale=Math.max(.0001,+primary.enemySpeedScale||1);for(let t=1;t<=turns;t++){let atk=0,boost=0,crit=0,critDmg=0,mast=0,aff=0,vuln=0,defdown=0,spd=0,cdr=0;for(const e of effects){const v=effectAt(e,t);if(!v)continue;switch(e.kind){case'atk':atk+=v;break;case'dmg':boost+=v;break;case'crit':crit+=v;break;case'critdmg':critDmg+=v;break;case'mastery':mast+=v;break;case'affinity':aff+=v;break;case'vuln':vuln+=v;break;case'defdown':defdown+=v;break;case'spd':spd+=v;break;case'cooldown':cdr+=v;break;} }
 const actionRatio=Math.sqrt((baseSpd*(1+spd/100)*scale)/(enemySpd*enemyScale));const acts=Math.max(0,Math.floor(t*actionRatio+1e-10)-Math.floor((t-1)*actionRatio+1e-10));const mult=(1+atk/100)*(1+boost/100)*(1+vuln/100)*(1+Math.min(80,defdown)/180)*(1+mast/500)*(1+aff/700)*(1+crit/250)*(1+critDmg/400)*(1+Math.min(3,cdr)*.045);const dmg=acts*baseD*mult;total+=dmg;if(dmg>0)events.push({turn:t,actions:acts,mult,dmg,atk,boost,vuln,defdown,spd,cdr});}
 return{score:total,events};}
function chaosTimeline(id,p){const candidates=p.candidates||[],count=Math.max(1,Math.min(3,+p.count||3)),beamW=Math.max(5,+p.beam||60),turns=Math.max(5,+p.turns||20),distinct=p.distinct!==false;let beam=[{rows:[],effects:[],score:timelineScore(p.primary,[],turns).score}],expanded=0;
 for(let slot=0;slot<count;slot++){const next=[];for(const b of beam){for(const c of candidates){if(cancelled.has(id))return{cancelled:true};if(distinct&&b.rows.some(x=>x.cls===c.cls))continue;const effects=b.effects.concat(c.effects||[]),res=timelineScore(p.primary,effects,turns);next.push({rows:b.rows.concat(c),effects,score:res.score,events:res.events});expanded++;if(expanded%200===0)post(id,'progress',{done:expanded,total:0,label:`support slot ${slot+1}`})}}next.sort((a,b)=>b.score-a.score);beam=next.slice(0,beamW)}return{best:beam[0]||null,rows:beam.slice(0,5),expanded};}
function acquisitionRank(id,p){const rows=[];let n=0;for(const x of p.items||[]){if(cancelled.has(id))return{cancelled:true};const prob=Math.max(0,+x.prob||0),gain=Math.max(0,+x.gain||0),runs=prob>0?1/prob:Infinity,mins=Number.isFinite(runs)?runs*(+p.minutes||3):Infinity;const value=gain>0?(prob>0?gain*prob:gain*.03):0;rows.push({...x,runs,mins,score:value});n++;if(n%250===0)post(id,'progress',{done:n,total:p.items.length})}rows.sort((a,b)=>b.score-a.score||b.gain-a.gain);return{rows:rows.slice(0,+p.topN||10),seen:n};}
onmessage=e=>{const {id,task,payload}=e.data||{};if(task==='cancel'){cancelled.add(id);return}try{let result;if(task==='comboRank')result=comboRank(id,payload||{});else if(task==='cartesianRank')result=cartesianRank(id,payload||{});else if(task==='chaosTimeline')result=chaosTimeline(id,payload||{});else if(task==='acquisitionRank')result=acquisitionRank(id,payload||{});else throw Error('Unknown worker task '+task);if(cancelled.has(id)){post(id,'cancelled');cancelled.delete(id)}else post(id,'done',{result});}catch(err){post(id,'error',{message:err?.message||String(err)})}}
